In [2]:
import pandas as pd
## Added this to mount my google drive to Google Colab run time - https://www.marktechpost.com/2019/06/07/how-to-connect-google-colab-with-google-drive/
from google.colab import drive 
drive.mount('/content/gdrive')

pre_df = pd.read_csv('/content/gdrive/My Drive/CS3244_Github_Repo/CS3244-ML/emotions_dataset_with_c_score.csv') 

df = pre_df.head(5000)

df.head()


Mounted at /content/gdrive


imdb_id  imdb_score                 genre  ...  calm  fear  confused
0   114709         8.3      Comedy|Adventure  ...     0    99         0
1   113497         6.9      Action|Adventure  ...     0     0         0
2   113228         6.6        Comedy|Romance  ...    13    17         0
3   114885         5.7  Comedy|Romance|Drama  ...     2     2         0
4   113041         5.9        Comedy|Romance  ...    68     0         3

[5 rows x 12 columns]

In [3]:
# add binary values to genres for multi label classification 
# 

drama = 'Drama'
comedy = 'Comedy'
romance = 'Romance'
action = 'Action'
crime = 'Crime'
thriller = 'Thriller'
horror = 'Horror'
adventure = 'Adventure'
documentary = 'Documentary'
mystery = 'Mystery'
family = 'Family'
fantasy = 'Fantasy'
# sci-fi = 'Sci-Fi'
biography = 'Biography'
animation = 'Animation'
history = 'History'
music = 'Music'
war = 'War'
short = 'Short'
western = 'Western'
musical = 'Musical'
sport = 'Sport'
# film-noir = 'Film-Noir'



df.insert(3, drama, 0)
df.insert(4, comedy, 0)
df.insert(5, romance, 0)
df.insert(6, action, 0)
df.insert(7, crime, 0)
df.insert(8, thriller, 0)
df.insert(9, horror, 0)
df.insert(10, adventure, 0)
df.insert(11, documentary, 0)
df.insert(12, mystery, 0)
df.insert(13, family, 0)
df.insert(14, fantasy, 0)
df.insert(15, 'Sci-Fi', 0)
df.insert(16, biography, 0)
df.insert(17, animation, 0)
df.insert(18, history, 0)
df.insert(19, music, 0)
df.insert(20, war, 0)
df.insert(21, short, 0)
df.insert(22, western, 0)
df.insert(23, musical, 0)
df.insert(24, sport, 0)
df.insert(25, 'Film-Noir', 0)


In [4]:
# sieve through each row and add in the appropiate binary multi-label classifications 

for index_label, row_series in df.iterrows():
  each_movie_genres = df.at[index_label, 'genre']
  array_of_genres = each_movie_genres.split('|')

  for genre in array_of_genres:

    if genre == 'Sci-Fi':
      df.at[index_label, 'Sci-Fi'] = 1
    
    if genre == 'Film-Noir':
      df.at[index_label, 'Film-Noir'] = 1

    if genre == drama:
      df.at[index_label, drama] = 1
    
    if genre == comedy:
      df.at[index_label, comedy] = 1

    if genre == romance:
      df.at[index_label, romance] = 1

    if genre == action:
      df.at[index_label, action] = 1

    if genre == crime:
      df.at[index_label, crime] = 1

    if genre == thriller:
      df.at[index_label, thriller] = 1

    if genre == horror:
      df.at[index_label, horror] = 1

    if genre == adventure:
      df.at[index_label, adventure] = 1

    if genre == documentary:
      df.at[index_label, documentary] = 1

    if genre == mystery:
      df.at[index_label, mystery] = 1

    if genre == family:
      df.at[index_label, family] = 1
    
    if genre == fantasy:
      df.at[index_label, fantasy] = 1

    if genre == biography :
      df.at[index_label, biography] = 1

    if genre == animation:
      df.at[index_label, animation] = 1

    if genre == history:
      df.at[index_label, history] = 1

    if genre == music:
      df.at[index_label, music] = 1

    if genre == war:
      df.at[index_label, war] = 1

    if genre == short:
      df.at[index_label, short] = 1

    if genre == western:
      df.at[index_label, western] = 1

    if genre == musical:
      df.at[index_label, musical] = 1
    
    if genre == sport:
      df.at[index_label, sport] = 1

df.head()

imdb_id  imdb_score                 genre  ...  calm  fear  confused
0   114709         8.3      Comedy|Adventure  ...     0    99         0
1   113497         6.9      Action|Adventure  ...     0     0         0
2   113228         6.6        Comedy|Romance  ...    13    17         0
3   114885         5.7  Comedy|Romance|Drama  ...     2     2         0
4   113041         5.9        Comedy|Romance  ...    68     0         3

[5 rows x 35 columns]

In [11]:
#separate dataset into training and test --- (validation?) 
import numpy as np
from sklearn.model_selection import train_test_split
#from sklearn.datasets import make_multilabel_classification

# this will generate a random multi-label dataset
# X, y = make_multilabel_classification(sparse = True, n_labels = 20,
# return_indicator = 'sparse', allow_unlabeled = False)
# print(X)
# print(y)

X_df = df.iloc[:,3:26]
y_df = df.iloc[:,26:]

# X = X_df.to_numpy()
# y = y_df.to_numpy()

X = np.asarray(df.iloc[:, 26:], dtype=np.float32)
y = np.asarray(df.iloc[:, 3:26], dtype=np.float32)
# # Todo -  repeat it for multiple times?

(X_train, X_test, Y_train, Y_test) = train_test_split(X, y, train_size=0.7, test_size=0.3)

print(X_train)
print(Y_train)

print(X_test.shape)
print(Y_test.shape)


[[ 4.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0. 50.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 1.  2.  0. ... 81.  7.  1.]
 [99.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  2.  0.  0.]]
[[1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(1500, 9)
(1500, 23)


### One vs Rest Classifier - SVC

In [12]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = OneVsRestClassifier(SVC()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

Hamming loss: 0.07591304347826087
F1 Score: [0.66349709 0.56062076 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### One vs Rest Classifier - NavieBayes 

In [15]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = OneVsRestClassifier(GaussianNB()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

[[1 0 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
Hamming loss: 0.09408695652173914
F1 Score: [0.66901055 0.51533742 0.32227488 0.15384615 0.15625    0.19047619
 0.15141956 0.06015038 0.         0.12749004 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest - Logistic Regression 

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Hamming loss: 0.07602898550724638
F1 Score: [0.65044248 0.52282158 0.         0.         0.         0.
 0.01219512 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest - Linear Regression 

In [24]:
from sklearn.linear_model import LinearRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = OneVsRestClassifier(LinearRegression()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Hamming loss: 0.07614492753623188
F1 Score: [0.65082873 0.50947368 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest Classifier - Perceptron 

In [31]:
from sklearn.linear_model import Perceptron
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = OneVsRestClassifier(Perceptron()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Hamming loss: 0.0958840579710145
F1 Score: [0.65123967 0.47958115 0.04699739 0.02290076 0.18111753 0.1106383
 0.02083333 0.         0.04030227 0.06593407 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### Random Forest Classifier

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = RandomForestClassifier(max_depth=50).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Hamming loss: 0.07976811594202898
F1 Score: [0.60609756 0.533205   0.10421836 0.05204461 0.06289308 0.01052632
 0.02380952 0.01036269 0.         0.0173913  0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### Neural Networks - MLP Classifier 

In [30]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Hamming loss: 0.07660869565217392
F1 Score: [0.62222222 0.57633588 0.02253521 0.03125    0.00727273 0.02234637
 0.04624277 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### k Nearest Neighbors 

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, Y_train)
predictions = knn_clf.predict(X_test)

h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Hamming loss: 0.08742028985507247
F1 Score: [0.58745476 0.52779953 0.124197   0.06849315 0.1396648  0.04587156
 0.07777778 0.00966184 0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### Multi-Label kNN

In [19]:
# http://scikit.ml/api/skmultilearn.adapt.mlknn.html
from skmultilearn.adapt import MLkNN
from sklearn.metrics import accuracy_score


classifier = MLkNN(k=10)

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



Accuracy Score: 0.098
Hamming loss: 0.07895652173913044
F1 Score: [0.57160804 0.50669413 0.02272727 0.06993007 0.         0.
 0.10471204 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### Binary Relevance - Gaussian NB

In [20]:
# https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/
!pip install scikit-multilearn
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import hamming_loss


classifier = BinaryRelevance(GaussianNB())
classifier.fit(X_train, Y_train)

# print(Y_test)
# print(predictions)
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



Accuracy Score: 0.11733333333333333
Hamming loss: 0.09408695652173914
F1 Score: [0.66901055 0.51533742 0.32227488 0.15384615 0.15625    0.19047619
 0.15141956 0.06015038 0.         0.12749004 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### Classifier Chains - Gaussian NB

In [21]:
## https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/
# using classifier chains
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB

# initialize classifier chains multi-label classifier
# with a gaussian naive bayes base classifier
classifier = ClassifierChain(GaussianNB())

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Accuracy Score: 0.04733333333333333
Hamming loss: 0.1235072463768116
F1 Score: [0.66901055 0.4884696  0.37353255 0.21256039 0.22978723 0.23060797
 0.28376068 0.01860465 0.03896104 0.13333333 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)


### Label Powerset - Gaussian NB 

In [22]:
# # https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/

# using Label Powerset
from skmultilearn.problem_transform import LabelPowerset
from sklearn.naive_bayes import GaussianNB

# initialize Label Powerset multi-label classifier
# with a gaussian naive bayes base classifier
classifier = LabelPowerset(GaussianNB())

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average=None)
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Accuracy Score: 0.019333333333333334
Hamming loss: 0.13997101449275362
F1 Score: [0.42824944 0.44282744 0.3121547  0.19784173 0.23003195 0.19854015
 0.25655977 0.25470333 0.12307692 0.12916667 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.        ]


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1515: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  average, "true nor predicted", 'F-score is', len(true_sum)
