In [1]:
import pandas as pd
## Added this to mount my google drive to Google Colab run time - https://www.marktechpost.com/2019/06/07/how-to-connect-google-colab-with-google-drive/
from google.colab import drive 
drive.mount('/content/gdrive')

pre_df = pd.read_csv('/content/gdrive/My Drive/CS3244_Github_Repo/CS3244-ML/emotions_dataset_with_c_score.csv') 

df = pre_df.head(5000)

df.head()


Mounted at /content/gdrive


imdb_id  imdb_score                 genre  ...  calm  fear  confused
0   114709         8.3      Comedy|Adventure  ...     0    99         0
1   113497         6.9      Action|Adventure  ...     0     0         0
2   113228         6.6        Comedy|Romance  ...    13    17         0
3   114885         5.7  Comedy|Romance|Drama  ...     2     2         0
4   113041         5.9        Comedy|Romance  ...    68     0         3

[5 rows x 12 columns]

In [2]:
# add binary values to genres for multi label classification 
# 

drama = 'Drama'
comedy = 'Comedy'
romance = 'Romance'
action = 'Action'
crime = 'Crime'
thriller = 'Thriller'
horror = 'Horror'
adventure = 'Adventure'
documentary = 'Documentary'
mystery = 'Mystery'
family = 'Family'
fantasy = 'Fantasy'
# sci-fi = 'Sci-Fi'
biography = 'Biography'
animation = 'Animation'
history = 'History'
music = 'Music'
war = 'War'
short = 'Short'
western = 'Western'
musical = 'Musical'
sport = 'Sport'
# film-noir = 'Film-Noir'



df.insert(3, drama, 0)
df.insert(4, comedy, 0)
df.insert(5, romance, 0)
df.insert(6, action, 0)
df.insert(7, crime, 0)
df.insert(8, thriller, 0)
df.insert(9, horror, 0)
df.insert(10, adventure, 0)
df.insert(11, documentary, 0)
df.insert(12, mystery, 0)
df.insert(13, family, 0)
df.insert(14, fantasy, 0)
df.insert(15, 'Sci-Fi', 0)
df.insert(16, biography, 0)
df.insert(17, animation, 0)
df.insert(18, history, 0)
df.insert(19, music, 0)
df.insert(20, war, 0)
df.insert(21, short, 0)
df.insert(22, western, 0)
df.insert(23, musical, 0)
df.insert(24, sport, 0)
df.insert(25, 'Film-Noir', 0)


In [3]:
# sieve through each row and add in the appropiate binary multi-label classifications 

for index_label, row_series in df.iterrows():
  each_movie_genres = df.at[index_label, 'genre']
  array_of_genres = each_movie_genres.split('|')

  for genre in array_of_genres:

    if genre == 'Sci-Fi':
      df.at[index_label, 'Sci-Fi'] = 1
    
    if genre == 'Film-Noir':
      df.at[index_label, 'Film-Noir'] = 1

    if genre == drama:
      df.at[index_label, drama] = 1
    
    if genre == comedy:
      df.at[index_label, comedy] = 1

    if genre == romance:
      df.at[index_label, romance] = 1

    if genre == action:
      df.at[index_label, action] = 1

    if genre == crime:
      df.at[index_label, crime] = 1

    if genre == thriller:
      df.at[index_label, thriller] = 1

    if genre == horror:
      df.at[index_label, horror] = 1

    if genre == adventure:
      df.at[index_label, adventure] = 1

    if genre == documentary:
      df.at[index_label, documentary] = 1

    if genre == mystery:
      df.at[index_label, mystery] = 1

    if genre == family:
      df.at[index_label, family] = 1
    
    if genre == fantasy:
      df.at[index_label, fantasy] = 1

    if genre == biography :
      df.at[index_label, biography] = 1

    if genre == animation:
      df.at[index_label, animation] = 1

    if genre == history:
      df.at[index_label, history] = 1

    if genre == music:
      df.at[index_label, music] = 1

    if genre == war:
      df.at[index_label, war] = 1

    if genre == short:
      df.at[index_label, short] = 1

    if genre == western:
      df.at[index_label, western] = 1

    if genre == musical:
      df.at[index_label, musical] = 1
    
    if genre == sport:
      df.at[index_label, sport] = 1

df.head()

imdb_id  imdb_score                 genre  ...  calm  fear  confused
0   114709         8.3      Comedy|Adventure  ...     0    99         0
1   113497         6.9      Action|Adventure  ...     0     0         0
2   113228         6.6        Comedy|Romance  ...    13    17         0
3   114885         5.7  Comedy|Romance|Drama  ...     2     2         0
4   113041         5.9        Comedy|Romance  ...    68     0         3

[5 rows x 35 columns]

In [4]:
#separate dataset into training and test --- (validation?) 
import numpy as np
from sklearn.model_selection import train_test_split
#from sklearn.datasets import make_multilabel_classification

# this will generate a random multi-label dataset
# X, y = make_multilabel_classification(sparse = True, n_labels = 20,
# return_indicator = 'sparse', allow_unlabeled = False)
# print(X)
# print(y)

X_df = df.iloc[:,3:26]
y_df = df.iloc[:,26:]

# X = X_df.to_numpy()
# y = y_df.to_numpy()

X = np.asarray(df.iloc[:, 26:], dtype=np.float32)
y = np.asarray(df.iloc[:, 3:26], dtype=np.float32)
# # Todo -  repeat it for multiple times?

(X_train, X_test, Y_train, Y_test) = train_test_split(X, y, train_size=0.7, test_size=0.3)

print(X_train)
print(Y_train)

print(X_test.shape)
print(Y_test.shape)


[[ 2.  4.  0. ... 76.  0.  0.]
 [ 8.  3.  1. ... 71.  5.  1.]
 [16.  1.  1. ... 44.  1.  0.]
 ...
 [ 2.  6. 10. ... 45.  1. 24.]
 [52.  0.  0. ... 46.  0.  0.]
 [ 0.  0.  0. ... 97.  0.  0.]]
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 1. ... 0. 0. 0.]
 [1. 1. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]]
(1500, 9)
(1500, 23)


### One vs Rest Classifier - SVC

In [6]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import SVC
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = OneVsRestClassifier(SVC()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

Accuracy Score: 0.10866666666666666
Hamming loss: 0.07655072463768116
F1 Score: 0.39523700480879326


### One vs Rest Classifier - NavieBayes 

In [7]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = OneVsRestClassifier(GaussianNB()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.088
Hamming loss: 0.0955072463768116
F1 Score: 0.39970850792494084


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest - Logistic Regression 

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = OneVsRestClassifier(LogisticRegression()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.10333333333333333
Hamming loss: 0.07701449275362318
F1 Score: 0.38223668914206


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest - Linear Regression 

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = OneVsRestClassifier(LinearRegression()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.10266666666666667
Hamming loss: 0.07710144927536232
F1 Score: 0.38024231127679403


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### One vs Rest Classifier - Perceptron 

In [11]:
from sklearn.linear_model import Perceptron
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = OneVsRestClassifier(Perceptron()).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.017333333333333333
Hamming loss: 0.1230144927536232
F1 Score: 0.2619130434782609


/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 10 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 11 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 12 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 13 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 14 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 15 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label not 16 is present in all training 

### Random Forest Classifier

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


clf = RandomForestClassifier(max_depth=50).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.102
Hamming loss: 0.0811304347826087
F1 Score: 0.3778617470549011


### Neural Networks - MLP Classifier 

In [13]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score

clf = MLPClassifier(random_state=1, max_iter=300).fit(X_train, Y_train)
predictions = clf.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")

Accuracy Score: 0.10666666666666667
Hamming loss: 0.07730434782608696
F1 Score: 0.41164791528788885


### k Nearest Neighbors 

In [14]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import hamming_loss
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


knn_clf = KNeighborsClassifier()
knn_clf.fit(X_train, Y_train)
predictions = knn_clf.predict(X_test)

h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")

print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Accuracy Score: 0.09133333333333334
Hamming loss: 0.08753623188405797
F1 Score: 0.371618809821057


### Multi-Label kNN

In [15]:
# http://scikit.ml/api/skmultilearn.adapt.mlknn.html
!pip install scikit-multilearn
from skmultilearn.adapt import MLkNN
from sklearn.metrics import accuracy_score


classifier = MLkNN(k=10)

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



     |████████████████████████████████| 92kB 3.7MB/s 
Accuracy Score: 0.098
Hamming loss: 0.08084057971014492
F1 Score: 0.37842656563405386


### Binary Relevance - Gaussian NB

In [16]:
# https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/
!pip install scikit-multilearn
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import hamming_loss


classifier = BinaryRelevance(GaussianNB())
classifier.fit(X_train, Y_train)

# print(Y_test)
# print(predictions)
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")



Accuracy Score: 0.088
Hamming loss: 0.0955072463768116
F1 Score: 0.39970850792494084


### Classifier Chains - Gaussian NB

In [17]:
## https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/
# using classifier chains
from skmultilearn.problem_transform import ClassifierChain
from sklearn.naive_bayes import GaussianNB

# initialize classifier chains multi-label classifier
# with a gaussian naive bayes base classifier
classifier = ClassifierChain(GaussianNB())

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Accuracy Score: 0.014666666666666666
Hamming loss: 0.13307246376811593
F1 Score: 0.35474349964862967


### Label Powerset - Gaussian NB 

In [19]:
# # https://www.analyticsvidhya.com/blog/2017/08/introduction-to-multi-label-classification/

# using Label Powerset
from skmultilearn.problem_transform import LabelPowerset
from sklearn.naive_bayes import GaussianNB

# initialize Label Powerset multi-label classifier
# with a gaussian naive bayes base classifier
classifier = LabelPowerset(GaussianNB())

# train
classifier.fit(X_train, Y_train)

# predict
predictions = classifier.predict(X_test)
h_loss = hamming_loss(Y_test, predictions)
f1 = f1_score(Y_test, predictions, average='micro')
a_score = accuracy_score(Y_test,predictions)

print(f"Accuracy Score: {a_score}")
print(f"Hamming loss: {h_loss}")
print(f"F1 Score: {f1}")


Accuracy Score: 0.017333333333333333
Hamming loss: 0.14707246376811595
F1 Score: 0.272231784279977
